### PR TITLE
add the links to paper reading videos

### PR DESCRIPTION
**Pull request by ksachdeva**

### CODE REVIEW

**Comment by dkozlov** [comment]
Hello, could you please add the year and author to each paper reading videos?

**Comment by ksachdeva** [comment]
> Hello, could you please add the year and author to each paper reading videos?

Good idea. Let me do that.

**Comment by dkozlov** [comment]
Thank you for the contribution!

**Comment by dkozlov** [comment]
Sorry, I think that the authors are incorrectly added. Please consider to add videos of original authors of the paper.

**Pull request merged**
