### PR TITLE
MGD: Matching Guided Distillation in ECCV 2020

### PR DESCRIPTION
**Pull request by kaiyuyue**
Add paper and implement of MGD - ECCV2020. Thanks in advance.

### CODE REVIEW

**Comment by dkozlov** [comment]
Hello @KaiyuYue ! Could you please add direct link to the arxiv (https://arxiv.org/abs/2008.09958) instead of http://kaiyuyue.com/mgd/?

**Comment by dkozlov** [comment]
Also please trim new line

**Comment by kaiyuyue** [comment]
Done. Please check it out. :)

**Comment by dkozlov** [comment]
Thank you for the contribution!

**Pull request merged**
